create table covid (
ID_COVID bigint NOT NULL PRIMARY KEY auto_increment,  
FECHA_ACTUALIZACION date ,
ID_REGISTRO varchar(10),
ORIGEN tinyint ,
SECTOR tinyint,
ENTIDAD_UM varchar(8),
SEXO tinyint,
ENTIDAD_NAC varchar(8),
ENTIDAD_RES varchar(8),
MUNICIPIO_RES varchar(10),
TIPO_PACIENTE tinyint,
FECHA_INGRESO date,
FECHA_SINTOMAS date ,
FECHA_DEF date,
INTUBADO tinyint,
NEUMONIA tinyint,
EDAD tinyint,
NACIONALIDAD tinyint,
EMBARAZO tinyint,
HABLA_LENGUA_INDIG tinyint,
INDIGENA tinyint,
DIABETES tinyint,
EPOC tinyint,
ASMA tinyint,
INMUSUPR tinyint,
HIPERTENSION tinyint,
OTRA_COM tinyint,
CARDIOVASCULAR tinyint, 
OBESIDAD tinyint,
RENAL_CRONICA tinyint,
TABAQUISMO tinyint,
OTRO_CASO tinyint,
TOMA_MUESTRA_LAB tinyint,
RESULTADO_LAB tinyint,
TOMA_MUESTRA_ANTIGENO tinyint,
RESULTADO_ANTIGENO tinyint,
CLASIFICACION_FINAL tinyint,
MIGRANTE tinyint,
PAIS_NACIONALIDAD varchar(15),
PAIS_ORIGEN varchar(5),
UCI tinyint 
);